source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem "jekyll"
gem "jekyll-gist"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem 'jekyll-target-blank'
gem "jekyll-remote-theme"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem "addressable", "2.7.0"
gem "colorator", "1.1.0"
gem "concurrent-ruby", "1.1.5"
gem "em-websocket", "0.5.1"
gem "eventmachine", "1.2.7"
gem "faraday", "1.0.0"
gem "ffi", "1.11.3"
gem "forwardable-extended", "2.6.0"
gem "http_parser.rb", "0.6.0"
gem "i18n", "1.8.0"
gem "jekyll-sass-converter", "2.0.1"
gem "jekyll-watch", "2.2.1"
gem "kramdown", "2.1.0"
gem "kramdown-parser-gfm", "1.1.0"
gem "liquid", "4.0.3"
gem "listen", "3.2.1"
gem "mercenary", "0.3.6"
gem "mini_portile2", "2.4.0"
gem "multipart-post", "2.1.1"
gem "nokogiri", "1.10.8"
gem "octokit", "4.15.0"
gem "pathutil", "0.16.2"
gem "public_suffix", "4.0.3"
gem "rb-fsevent", "0.10.3"
gem "rb-inotify", "0.10.1"
gem "rouge", "3.14.0"
gem "safe_yaml", "1.0.5"
gem "sassc", "2.2.1"
gem "sawyer", "0.8.2"
gem "terminal-table", "1.8.0"
gem "unicode-display_width", "1.6.0"
gem "wdm", "0.1.1"
